version: '3'

services:

  # runs Nginx, PHP, webapp(s) on this machine
  dev_webserver:

    # Want to debug this container?
    #   After 'docker-compose build' and 'docker-compose up'
    #   run: 'docker-compose exec dev_webserver bash' and investigate...
    #entrypoint: ["sh", "-c", "sleep 2073600"]

    build:
      # path to Dockerfile from this file
      context: .
      # name of Dockerfile
      dockerfile: ./dockerfiles/webserver.Dockerfile

    ports:
      # map host's port 80 (left) to container's port 80 (right)
      # ...container port and host port are expected to be open...
      - "81:80"
      # same as above: maps external port <-> internal port
      - "444:443"
  
    depends_on:
      # does not start this service until database + certbot services start
      - dev_certbot
      - dev_database

    # map each named volume to a specified folder/file in container
    volumes:
      #- ./:/var/www/html # copy from here to there... <-- this makes no sense, why would you want to save the laravel project as a volume???
      - /docker/volumes/php:/usr/local/etc/php/php.ini # map host server dir to container file...
      - /docker/volumes/nginx_logs:/var/log/nginx # map host server dir to container dir...
      - /docker/volumes/cron:/var/spool/cron # map host server dir to container dir...
      - ./server/vhost.conf:/etc/nginx/conf.d/app.conf # map host server file to container file...
      - ./server/certbot/conf:/etc/letsencrypt # map host server dir to container dir...
      - ./server/certbot/www:/var/www/certbot # map host server dir to container dir...

  # runs MySQL on this machine
  dev_database:

    # Want to debug this container?
    #   After 'docker-compose build' and 'docker-compose up'
    #   run: 'docker-compose exec dev_database bash' and investigate...
    #entrypoint: ["sh", "-c", "sleep 2073600"]

    build:
      context: .
      dockerfile: ./dockerfiles/database.Dockerfile
    
    ports:
      - "3307:3306"

    # env variables for this container
    environment:
      MYSQL_DATABASE: my_default_db
      MYSQL_ROOT_PASSWORD: secret

    command:
      --init-file /data/application/init.sql
    
    # always auto-restart regardless of how the container exited (except some cases)
    restart: unless-stopped

    volumes:
      - /docker/volumes/mysql:/var/lib/mysql
      - /docker/volumes/mysql_logs:/var/log/mysql
      - ./server/init.sql:/data/application/init.sql

  # runs PhpMyAdmin on this machine
  dev_admin:

    # Want to debug this container?
    #   After 'docker-compose build' and 'docker-compose up'
    #   run: 'docker-compose exec dev_admin bash' and investigate...
    #entrypoint: ["sh", "-c", "sleep 2073600"]

    build:
      context: .
      dockerfile: ./dockerfiles/admin.Dockerfile

    ports:
      - "8000:80"

    restart: unless-stopped

    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: dev_database
    
    depends_on:
      - dev_database

  # uses letsencrypt service to auto-renew SSL certificates on expire (check every 12 hrs)
  dev_certbot:

    build:
      context: .
      dockerfile: ./dockerfiles/certbot.Dockerfile

    restart: unless-stopped
    
    volumes:
      - ./server/certbot/conf:/etc/letsencrypt
      - ./server/certbot/www:/var/www/certbot
      - /etc/letsencrypt/digitalocean.ini:/etc/letsencrypt/digitalocean.ini # comment out if you are running certbot/certbot instead of certbot/dns-dnsprovider

    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'